Updated Dockerfile to build custom php with gd

diff --git a/php-imagick/Dockerfile b/php-imagick/Dockerfile
--- a/php-imagick/Dockerfile
+++ b/php-imagick/Dockerfile
@@ -1,7 +1,7 @@
-FROM php:8.4.15-cli-alpine3.22
+FROM php:8.5.7-cli-alpine3.24
 
 # Some imagick formats have been separated into own packages:
-# https://pkgs.alpinelinux.org/packages?name=imagemagick-*&branch=v3.22&repo=&arch=aarch64&origin=&flagged=&maintainer=
+# https://pkgs.alpinelinux.org/packages?name=imagemagick-*&branch=v3.24&repo=&arch=aarch64&origin=&flagged=&maintainer=
 
 # Install dependencies and development tools
 RUN apk add --update --no-cache \
@@ -14,6 +14,11 @@ RUN apk add --update --no-cache \
     imagemagick-heic \
     imagemagick-jxl \
     imagemagick-dev \
+    zlib-dev \
+    libpng-dev \
+    libjpeg-turbo-dev \
+    freetype-dev \
+    libwebp-dev \
     gcc \
     g++ \
     make \
@@ -35,8 +40,13 @@ RUN docker-php-ext-enable imagick
 # Install pdo_mysql
 RUN docker-php-ext-install pdo_mysql
 
-# Clean up to reduce image size
-RUN apk del git gcc g++ make autoconf pkgconfig imagemagick-dev && \
-    rm -rf /var/cache/apk/* /tmp/imagick
+# GD requires zlib, linpng, libjpeg, freetype2, libwebp 
+RUN set -eux; \
+    docker-php-ext-configure gd --with-freetype --with-jpeg --with-webp; \
+    docker-php-ext-install exif gd
 
-    
+# Clean up to reduce image size
+RUN apk del git gcc g++ make autoconf pkgconfig imagemagick-dev zlib-dev libpng-dev libjpeg-turbo-dev freetype-dev libwebp-dev && \
+    rm -rf /var/cache/apk/* /tmp/imagick 
+
+
